### ISSUE TITLE
Displaying doesn't work

### ISSUE THREAD

**Issue by svvac** [DavidBM/pixi-nativeGLline#1]
Displaying a `PIXI.Graphics` object fails (displays nothing, no error) when using this patch/lib, although rendering a texture and using a sprite to display it works.

Using latest stable PIXI version

**Comment by DavidBM** [comment]
Ok, I will check. Thanks!
(can you post a code?)

**Comment by DavidBM** [comment]
Solved in ed99b95ac1b8040bb7b7c91bd2a16641d7c3a8fd

I update the code to the latest pixi.js versión. Thanks! :D

**Comment by svvac** [comment]
Wow, that was fast, many thanks!

Although I believe you're missing the following line at the beginning of the script:

``` javascript
PIXI.WebGLGraphics.buildPolygonLine = PIXI.WebGLGraphics.buildLine;
```

Cheers!

**Comment by DavidBM** [comment]
Ops! my fault. Solved!
7a7e006cd65f1f099b3e1a237a90edc8223a6d9d

**Comment by svvac** [comment]
Me again ^^

I'm having trouble displaying native lines next to polygon lines on the same `PIXI.Graphics` object.

After drawing a bunch of 1px lines, I change the `lineStyle` to display 2px lines. I draw one, which appears, but causes all 1px lines to disappear. As soon as I switch `lineStyle` to 1px width again, those reappear, but the 2px line disappears. And again If I draw another 2px line...

Note that changing `lineStyle` back to 1px makes the nativeLines reappear, but I need to **draw** a 2px line for those to reappear

**Comment by DavidBM** [comment]
Hi!

That is relatively expected. This library tries to obtain more performance drawing GL_LINES instead of GL_TRIANGLE. To archieve that this library creates a native WebGL GL_LINE mesh, not the normal, GL_TRIANGLE pixi-created one. 

Technically, the lines need to be repolygonized whenever any parameter changes. But i don't know why it won't repolygonize all lines. Try setting the  `PIXI.Graphics.dirty` param to true in your Graphics object.

I will investigate this more, but for now, it the mentioned solution fails, try making a Graphics object for 1px lines and another for any other width lines.

**Comment by DavidBM** [comment]
Hi @svvac . 

I hope you solve your problem. In any case, this patch can't solve your situation. You must use tho Graphics objects. One for drawing the 1px lines and other for the rest. The 1px lines will draw very fast, the others, as expected, at the normal speed (that is very fast too!). 

For solving this problem all graphic object code library should be rewrite for having this optimization in mind. Or at least for including something like plugins, but this will affect to the performance. Anyway, two graphics objects and it should work correctly.

I will close this issue. The work of rewriting all graphic object is too much.

**Comment by DavidBM** [comment]
Hey!

I made this pull request for pixijs

If you like to have this feature in the official pixijs, support it! 

https://github.com/pixijs/pixi.js/pull/3328
